### ISSUE TITLE
Not a real issue

### ISSUE THREAD

**Issue by wynok** [Aida-Enna/XIVPlugins#1]
Hello,

its not a real issue more a nice to have for the autosync and it works fine btw thanks for that plugin :)
Could you set autostance for tanks too ? that is the most shitty mechanic in ff >_>

If not its anyway a nice plugin thanks for the work !

**Comment by Aida-Enna** [comment]
Awww, no problem! Happy to help! And that's actually not a bad idea! I'll see what I can do 👍

**Comment by Aida-Enna** [comment]
Added auto tank stance swapping in https://github.com/Aida-Enna/XIVPlugins/commit/a739a27807416786859dffbed31e0a39617b6d0a

Thanks for the suggestion!
