### ISSUE TITLE
grid bug

### ISSUE THREAD

**Issue by Battler624** [Aida-Enna/XIVPlugins#11]
I've been facing an issue and it got narrowed it down to AutoLogin. 
Here is an image of my own testing that shows the grid issue
https://i.imgur.com/gbUzOO6.png

**Comment by Aida-Enna** [comment]
Yeahhhhhh, I noticed this but it didn't affect functionality as far as I can tell? I have no idea why it randomly started happening, I didn't change the code. Once I finish some plugin updates, I'll take a look and see why.

Let me know if it is interfering or breaking something though and I'll move it up on the priority list.

**Comment by Battler624** [comment]
Nope it's not interfering with anything at all, take your time with it.

**Comment by Theletha** [comment]
> Yeahhhhhh, I noticed this but it didn't affect functionality as far as I can tell? I have no idea why it randomly started happening, I didn't change the code. Once I finish some plugin updates, I'll take a look and see why.
> 
> Let me know if it is interfering or breaking something though and I'll move it up on the priority list.

For me it does, i can't press the datacenter button so i can't switch unless i unload it. also the screen is very dark since i use auto hdr too.

**Comment by Aida-Enna** [comment]
Sorry to hear that, I'll take a look tonight then.

**Comment by Battler624** [comment]
any news on this @Aida-Enna

**Comment by Aida-Enna** [comment]
Not yet - I went to check it out only for there to be 24 XIV maint, followed by a huge PSO2 update that I'm still working through. I'll try to take a look as soon as I can, it's on my todo list as I go through it. Sorry!

**Comment by Aida-Enna** [comment]
Fixed in the latest live version, sorry that took so long
