### ISSUE TITLE
Loot Master broken after 6.5 update

### ISSUE THREAD

**Issue by AetherCollective** [Aida-Enna/XIVPlugins#18]
Hey just creating a ticket since one wasn't made already. Wife and I use the plugin and have been missing it. Hope it can be updated when you have some free time. Thanks and have a great day

**Comment by Aida-Enna** [comment]
Heya! What aspect of it is broken? I updated the backend stuff and tested a few things and they seemed to work fine. Are you using the latest, 1.0.0.5?

**Comment by AetherCollective** [comment]
Yes I am. It says it's outdated and needs to be updated by the author. ![image](https://github.com/Aida-Enna/XIVPlugins/assets/7028351/0a49253f-0c8a-41fe-9a33-252122f5aa76)

**Comment by Aida-Enna** [comment]
Odd, let me try bumping the version in the JSON.

**Comment by Aida-Enna** [comment]
Try rebooting your game (to force it to get the new JSON instead of a cached one) and lemme know if the update shows/works.

**Comment by AetherCollective** [comment]
It just updated. Weird, I've been manually hitting the update button every few hours while I play and it never downloaded. Thanks!
