### ISSUE TITLE
Autologin can't run on the Chinese server

### ISSUE THREAD

**Issue by mokeling** [Aida-Enna/XIVPlugins#3]
Autologin can't run on the Chinese server. Although I can choose the Chinese server in the settings, it will crash when I log in.

This is my log, I don't know if it is useful.
[dalamud_appcrash_20221227_022934_272_22400.log](https://github.com/Aida-Enna/XIVPlugins/files/10304519/dalamud_appcrash_20221227_022934_272_22400.log)

**Comment by Aida-Enna** [comment]
I don't have access to the Chinese version of XIV, so I unfortunately have no way of testing this to see what's going on =/ Sorry!
