### ISSUE TITLE
Loot Master - Rolling /greed will pass on items already greeded

### ISSUE THREAD

**Issue by alsnana** [Aida-Enna/XIVPlugins#4]
Hi there,

Thanks for this plugin, it really saves me from having to constantly click and need/greed on items. I've bound and macro'd /greed so that anytime I go through an expert or leveling roulette, I just click the macro button instead of clicking on a specific item and needing/greeding it.

However it seems like if you /greed an item that was picked from a previous chest, then pick up another chest, then /greed again, it will pass on the first item/the rest of your currently greeded items. I'm not sure if it's intentional, but if it is, maybe adding a /greedall would be useful to always greed instead of passing?

Thanks for this!

**Comment by Aida-Enna** [comment]
Heya! Glad to hear you're enjoying it! I'll go ahead and take a look, thanks for reporting this bug!

**Comment by Aida-Enna** [comment]
Fixed in https://github.com/Aida-Enna/XIVPlugins/commit/1e86a67c151fabd22bfbe4aa725699e9ad40684c 👍 Will be live soon.
